source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'EMSpeed_Example' do
  pod "EMSpeed", :path => "../"
  
  target 'EMSpeed_Tests' do
      
  end
  
  target 'Today' do
      inherit!:search_paths
#      pod "EMSpeed/Network", :path => "../"
  end
  
end



