source 'https://github.com/CocoaPods/Specs.git'


target 'EMSpeed_Example' do
  pod "EMSpeed", :path => "../"

  
end

target 'EMSpeed_Tests' do
    
end

target 'Today' do
    # inherit!:search_paths
    #      pod "EMSpeed/Network", :path => "../"
    pod "EMSpeed", :path => "../"

end



