# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'UIDemo' do
    
    pod 'EMSpeed', :path=>"../../"
    pod 'ZipArchive', '~> 1.3.0'
end

target 'UIDemoTests' do
    
end
